Math 4e Cahier des compétances

page 11

**30 Pour les experts**

Quels sont tous les nombres à 1, 2 ou 3 chiffres qui sont à la fois le carré d'un nombre et aussi le cube d'un nombre ?

*Solution 1*

-----------------

Soit $a, b, m, n$ des nombres naturels, $a, b, m, n \in \mathbb{N}$.

$n$ doit être un carré parfait : $n = a^2$

$n$ doit être un cube parfait : $n = b^3$

Alors : $n = a^2 = b^3$, donc $a = b^{3/2}$ et $b = a^{2/3}$.

Comme  $a = b^{3/2}$ et $a$ doit être entier, alors $b$ doit être un carré parfait, $b = m^2$.

Comme $b = m^2 = a^{2/3}$, alors $(m^2)^3 = (a^{2/3})^3$, c. à d. $a^2 = (m^2)^3$. Mais $a^2= n$. 

Donc $n = (m^2)^3 = m^6$ où $m$ est un nombre naturel, $m \in \mathbb{N}$.



In [29]:
%reset -f
import numpy as np

m = 0; n = (m**2)**3; print(n, np.sqrt(n), np.cbrt(n))
m = 1; n = (m**2)**3; print(n, np.sqrt(n), np.cbrt(n))
m = 2; n = (m**2)**3; print(n, np.sqrt(n), np.cbrt(n))
m = 3; n = (m**2)**3; print(n, np.sqrt(n), np.cbrt(n))

0 0.0 0.0
1 1.0 1.0
64 8.0 4.0
729 27.0 9.0


In [68]:
print(' m    n    n½   n⅓')
m = 0; n = (m**2)**3; print(f'{m:2d} {n:4.0f} {np.sqrt(n):4.0f} {np.cbrt(n):4.0f}')
m = 1; n = (m**2)**3; print(f'{m:2d} {n:4.0f} {np.sqrt(n):4.0f} {np.cbrt(n):4.0f}')
m = 2; n = (m**2)**3; print(f'{m:2d} {n:4.0f} {np.sqrt(n):4.0f} {np.cbrt(n):4.0f}')
m = 3; n = (m**2)**3; print(f'{m:2d} {n:4.0f} {np.sqrt(n):4.0f} {np.cbrt(n):4.0f}')

 m    n    n½   n⅓
 0    0    0    0
 1    1    1    1
 2   64    8    4
 3  729   27    9


Trouver les carrés et cubes parfaits de $0$ à $n_{max}$ en utilisant la boucle `while`.

In [65]:
n_max = 1e3
m = 0
n = (m**2)**3
print(' m   n   n½  n⅓')
while n < n_max:
    print(f'{m:2d} {n:3.0f} {np.sqrt(n):3.0f} {np.cbrt(n):3.0f}')
    m += 1
    n = (m**2)**3;

 m   n   n½  n⅓
 0   0   0   0
 1   1   1   1
 2  64   8   4
 3 729  27   9


Le même solution mais avec un boucle `repeat .. until`.

In [66]:
n_max = 1e3
m = 0
print(' m   n   n½  n⅓')
while True:
    n = (m**2)**3
    if n > n_max: break
    print(f'{m:2d} {n:3.0f} {np.sqrt(n):3.0f} {np.cbrt(n):3.0f}')
    m += 1

 m   n   n½  n⅓
 0   0   0   0
 1   1   1   1
 2  64   8   4
 3 729  27   9


*Solution 2*

--------
Je trouve les nombres les plus grands qui ont le carré et le cube plus petit que 1000 : 

In [5]:
import numpy as np
print(round(np.sqrt(1000)), 'et', round(np.cbrt(1000)))

32 et 10


Je construit deux ensambles, un des carrés et un des cubes.

In [6]:
squares = set(n**2 for n in np.arange(0, 32))
cubes = set(n**3 for n in np.arange(0, 10))

Je vois quelles sont les nombres communs dans les deux ensambles des carrés et des cubes : 

In [7]:
common = set.intersection(squares, cubes)

J'affiche les résultat :

In [8]:
a_common = np.array(list(common))
print(a_common)
print(np.sqrt(a_common))
print(np.cbrt(a_common))

print(['{:4.0f}'.format(i) for i in a_common])
print(['{:4.0f}'.format(i) for i in np.sqrt(a_common)])
print(['{:4.0f}'.format(i) for i in np.cbrt(a_common)])

[  0   1  64 729]
[ 0.  1.  8. 27.]
[0. 1. 4. 9.]
['   0', '   1', '  64', ' 729']
['   0', '   1', '   8', '  27']
['   0', '   1', '   4', '   9']


*Solution 3*

-------

J'essaye tous les racines carrées et cubes.

Prend un nombre.

Vérifie si la racine carré est un entier.

- Si oui, vérifie si la racine cubique est entier;
    - Si oui, affiche le résultat.

In [9]:
for n in np.arange(0, 1e3):
    sqrt_n = np.sqrt(n)
    if sqrt_n.is_integer():
        cbrt_n = np.cbrt(n)
        if cbrt_n.is_integer():
            print(f'{n:6.0f}, {sqrt_n:6.0f}, {cbrt_n:6.0f}')

     0,      0,      0
     1,      1,      1
    64,      8,      4
   729,     27,      9


Solution en faisant racine carrée des cubes :

In [10]:
cubes = np.array(list(n**3 for n in np.arange(0, 10)))
np.array([cubes, np.sqrt(cubes)]).T

array([[  0.        ,   0.        ],
       [  1.        ,   1.        ],
       [  8.        ,   2.82842712],
       [ 27.        ,   5.19615242],
       [ 64.        ,   8.        ],
       [125.        ,  11.18033989],
       [216.        ,  14.69693846],
       [343.        ,  18.52025918],
       [512.        ,  22.627417  ],
       [729.        ,  27.        ]])