Math 4e Cahier des compétances

**11. Pour les experts**

Voici le début d'une suite :

In [1]:
import numpy as np
s = np.array([1, 2, 5, 10, 17, 26, 37, 50])

Trouve l'expression qui permet de décrire cette suite.

Faire la difference entre les éléménts consécutives :

In [2]:
np.ediff1d(s)

array([ 1,  3,  5,  7,  9, 11, 13])

L'expression qui décrit cette suite : 

$$x_0 = 1;$$

$$x_{n + 1} = x_n + 2  n + 1, n = 0 ... n_{max}$$

On fait cette expression 'pas à pas' :

In [3]:
import numpy as np
n_max = 10                # nombre max d'éléments 

x = np.empty((n_max, 1))  # liste vide
x[:] = np.nan             # liste avec 'nan'
x[0] = 1
x[1] = x[0] + 2 * 0 + 1
x[2] = x[1] + 2 * 1 + 1
x[3] = x[2] + 2 * 2 + 1
x[4] = x[3] + 2 * 3 + 1
x[5] = x[4] + 2 * 4 + 1
x[6] = x[5] + 2 * 5 + 1
x[7] = x[6] + 2 * 6 + 1
x.T

array([[ 1.,  2.,  5., 10., 17., 26., 37., 50., nan, nan]])

On fait cette expression en utilisant $n$ et la formule : $x_0 = 1$, $x_{n + 1} = x_n + 2  n + 1$

In [4]:
x = np.empty((n_max, 1))
x[:] = np.nan
x[0] = 1
n = 0; x[n + 1] = x[n] + 2 * n + 1
n = 1; x[n + 1] = x[n] + 2 * n + 1
n = 2; x[n + 1] = x[n] + 2 * n + 1
n = 3; x[n + 1] = x[n] + 2 * n + 1
n = 4; x[n + 1] = x[n] + 2 * n + 1
n = 5; x[n + 1] = x[n] + 2 * n + 1
n = 6; x[n + 1] = x[n] + 2 * n + 1
n = 7; x[n + 1] = x[n] + 2 * n + 1
n = 8; x[n + 1] = x[n] + 2 * n + 1
x.T

array([[ 1.,  2.,  5., 10., 17., 26., 37., 50., 65., 82.]])

On fait cette expression en utilisant `for` et la formule : $x_0 = 1$, $x_{n + 1} = x_n + 2  n + 1$

In [8]:
x = np.empty((n_max, 1))
x[:] = np.nan
x[0] = 1
for n in np.arange(0, n_max-1):
    x[n + 1] = x[n] + 2 * n + 1
x.T

array([[ 1.,  2.,  5., 10., 17., 26., 37., 50., 65., 82.]])